version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Dockerクライアントをインストール
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o ~/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xzf ~/docker-$VER.tgz
            sudo mv ~/project/docker/* /usr/bin

      - run:
          name: Docker Composeをインストール
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: ディレクトリの内容を確認
          command: |
            cd
            ls -al
            ls -al ~/project
            cd ~/project/plain_c0
            sudo docker-compose up -d

