version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.06.0-ce

      - run:
          name: Docker Composeをインストール
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: ディレクトリの内容を確認
          command: |
            cd
            ls -al
            ls -al ~/project
            cd ~/project/plain_c0
            sudo -E env
            sudo -E docker-compose up -d

