#!/bin/bash
set -eu

TCP_PORT=1666
P4PORT="--build-arg P4PORT=${TCP_PORT}"
P4_SUPER_USER=super
P4_SUPER_PASSWD=He1ixC@re
P4_SERVER_ID=commit
P4_UNICODE=--unicode
P4_CASE=
P4_SAMPLE_DEPOT=

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

case "$DOCKER_TAG" in
  *_sample* )
  P4_SAMPLE_DEPOT="--build-arg P4_SAMPLE_DEPOT=1"
  ;;&
  *_ssl* )
  P4PORT="--build-arg P4PORT=ssl:${TCP_PORT}"
  ;;&
  *_c0* )
  P4_CASE="--build-arg P4_CASE=0"
  ;;
  *_c1* )
  P4_CASE="--build-arg P4_CASE=1"
  ;;
esac

echo docker build --build-arg TCP_PORT=${TCP_PORT} --build-arg P4_SUPER_USER=${P4_SUPER_USER} --build-arg P4_SUPER_PASSWD=${P4_SUPER_PASSWD} --build-arg P4_SERVER_ID=${P4_SERVER_ID} --build-arg P4_UNICODE=${P4_UNICODE} ${P4PORT} ${P4_CASE} ${P4_SAMPLE_DEPOT} ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

docker build --build-arg TCP_PORT=${TCP_PORT} --build-arg P4_SUPER_USER=${P4_SUPER_USER} --build-arg P4_SUPER_PASSWD=${P4_SUPER_PASSWD} --build-arg P4_SERVER_ID=${P4_SERVER_ID} --build-arg P4_UNICODE=${P4_UNICODE} ${P4PORT} ${P4_CASE} ${P4_SAMPLE_DEPOT} ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .
