#!/bin/bash
set -eu

TCP_PORT=1666
P4_SUPER_USER=super
P4_SUPER_PASSWD=He1ixC@re
P4_SERVER_ID=commit
P4_UNICODE=--unicode
P4_CASE=
P4_SSL=

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

case "$DOCKER_TAG" in
  *_ssl* )
  P4_SSL='--build-arg P4_SSL=ssl'
  ;;&
  *_c0* )
  P4_CASE='--build-arg P4_CASE=0'
  ;;
  *_c1* )
  P4_CASE='--build-arg P4_CASE=1'
  ;;
esac

docker build --build-arg TCP_PORT=${TCP_PORT} --build-arg P4_SUPER_USER=${P4_SUPER_USER} --build-arg P4_SUPER_PASSWD=${P4_SUPER_PASSWD} --build-arg P4_SERVER_ID=${P4_SERVER_ID} --build-arg P4_UNICODE=${P4_UNICODE} ${P4_SSL} ${P4_CASE} ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .
